import os

DJANGO_SECURE = os.getenv("DJANGO_SECURE", "false").lower() == "true"

DEBUG = not DJANGO_SECURE

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = [
    "https://127.0.0.1",
    "https://localhost",
    "https://127.0.0.1:8443",
]


SESSION_COOKIE_SECURE = DJANGO_SECURE
CSRF_COOKIE_SECURE = DJANGO_SECURE

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


SECURE_SSL_REDIRECT = DJANGO_SECURE

SECURE_HSTS_SECONDS = 31536000 if DJANGO_SECURE else 0

SECURE_HSTS_INCLUDE_SUBDOMAINS = DJANGO_SECURE

SECURE_HSTS_PRELOAD = False


SECURE_CONTENT_TYPE_NOSNIFF = DJANGO_SECURE

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

X_FRAME_OPTIONS = "DENY"



CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)